services:
  - type: web
    name: inventory-backend
    env: node
    plan: free
    startCommand: npm start
    buildCommand: npm install
    envVars:
      - key: NODE_ENV
        value: production
